import 'dotenv/config'

const SERVER_PORT = process.env.SERVER_PORT
const DATABASE_HOST=process.env.DATABASE_HOST
const DATABASE_PORT=process.env.DATABASE_PORT
const DATABASE_NAME=process.env.DATABASE_NAME
const DATABASE_USERNAME=process.env.DATABASE_USERNAME
const SECRET=process.env.SECRET

export {SERVER_PORT, DATABASE_HOST, DATABASE_PORT, DATABASE_NAME, DATABASE_USERNAME, SECRET}